<a href="https://colab.research.google.com/github/DomSarr/data_science_example_1/blob/main/wprowadzenie_numpy/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy  as np
np.__version__

'2.0.2'

In [ ]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__annotations__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', '

Array 1D

In [ ]:
x=np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
x.shape

(2,)

In [ ]:
x.ndim

1

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

Array 2D

In [ ]:
x=np.array([[1,3],[-2,8]])
x

array([[ 1,  3],
       [-2,  8]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x=np.array([[1,2,3],[4,5,8]])
print(x)

[[1 2 3]
 [4 5 8]]


In [ ]:
x.shape

(2, 3)

Array 3D

In [ ]:
x=np.array(
    [[[3,2,1],[7,8,9]],
     [[3,4,3],[9,8,7]],
     [[4,3,2],[1,2,3]]
    ]
)
x

array([[[3, 2, 1],
        [7, 8, 9]],

       [[3, 4, 3],
        [9, 8, 7]],

       [[4, 3, 2],
        [1, 2, 3]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)

# Typy danych

In [ ]:
A= np.array([1,2,3], dtype=float)
A.dtype

dtype('float64')

In [ ]:
A=np.array([True,False])
A.dtype

dtype('bool')

Tworzenie tabel

In [ ]:
np.zeros(shape=(4,8), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,4), fill_value=5, dtype=int)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10,stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.linspace(start=10,stop=11,num=11, dtype=float)

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ])

In [ ]:
A=np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Operacje na tablicach

In [ ]:
import numpy as np

In [ ]:
A= np.array([3,1,4,2])
B= np.array ([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B


array([6, 0, 7, 4])

In [ ]:
np.add(A,B)

array([6, 0, 7, 4])

In [ ]:
A-B

array([0, 2, 1, 0])

In [ ]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [ ]:
A*B

array([ 9, -1, 12,  4])

In [ ]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A+3


array([6, 4, 7, 5])

Mnożenie macierzy przez siebie

In [ ]:
X=np.array([[1,3],[-2,0]])
Y=np.array([[6,0],[-1,2]])
print(X,'\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X & Y

array([[ 0,  0],
       [-2,  0]])

# Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

Losowa wartośc z rozkłądu normalnego

In [ ]:
np.random.randn()

1.764052345967664

10 losowych wartosci z rozkłądu normalnego

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

Rozkłąd normalny 10 wierszy(10 próbek), 4 kolumny


In [ ]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

Rozkład jednostajny na przedziale

In [ ]:
np.random.rand()

0.1965823616800535

In [ ]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [ ]:
np.random.rand(10,2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

Zwracanie wartości wiekśzej od zera i mniejszej od 10

In [ ]:
np.random.randint(10)

3

Losowa liczba z przedziału

In [ ]:
np.random.randint(low=10,high=101)

56

Losowe liczby z przedziału i określenie ich ilości

In [ ]:
np.random.randint(low=10,high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

Wybieranie losowo z podanej listy

In [ ]:
np.random.choice([4,2,3,6,9,5])

np.int64(4)

In [ ]:
np.random.choice(['python', 'java', 'sql'])

np.str_('python')

Przykłąd przetsowania

In [ ]:
data=np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([6, 9, 1, 5, 0, 7, 3, 4, 8, 2])

# Podstawowe funkcje

In [ ]:
np.exp(1)

np.float64(2.718281828459045)

In [ ]:
np.sqrt(4)

np.float64(2.0)

Jeżeli jedna wartośc nie jest wartości logiczną zwróci false

In [ ]:
np.all([2,3,1])

np.True_

Jeżeli wszytskie wartosci nie sa logiczne zwroci false

In [ ]:
np.any([0,0,0])

np.False_

In [ ]:
A=np.random.rand(5)
A

array([0.58127287, 0.88173536, 0.69253159, 0.72525428, 0.50132438])

Największa wartość(pokazuje pozycje liczy się od 0)

In [ ]:
np.argmax(A)

np.int64(1)

In [ ]:
np.max(A)

np.float64(0.8817353618548528)

In [ ]:
A[np.argmax(A)]

np.float64(0.8817353618548528)

In [ ]:
np.argmin(A)

np.int64(4)

In [ ]:
np.min(A)

np.float64(0.5013243819267023)

Sortowanie od min do max po indeksach oraz wartosciach

> Dodaj cytat blokowy



In [ ]:
np.argsort(A)

array([4, 0, 2, 3, 1])

In [ ]:
np.sort(A)

array([0.50132438, 0.58127287, 0.69253159, 0.72525428, 0.88173536])

Średnia

In [ ]:
np.mean(A)

np.float64(0.676423697262964)

Mediana

In [ ]:
np.median(A)

np.float64(0.6925315900777659)

Odchylenie standardowe

In [ ]:
np.std(A)

np.float64(0.13000786074672221)

# Wycinanie i indeksowanie

In [6]:
A=np.arange(20)
A


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:start], A[stop:]

In [ ]:
A[2]

np.int64(2)

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A[[0,2]]

array([0, 2])

z minusem czyli od końca

In [ ]:
A[-1]

np.int64(19)

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

Działąnia wycinania na tablicach

In [7]:
A=A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[0]

array([0, 1, 2, 3, 4])

Wycinanie kolumny

In [ ]:
A[:,0]

array([ 0,  5, 10, 15])

In [ ]:
A[:,-1]

array([ 4,  9, 14, 19])

Wycinanie konkretnej wartosci

In [ ]:
A[1,3]

np.int64(8)

Wycinek z tablicy( zakres wierszy:zakres kolumn)

In [ ]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [8]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[2:4,2:4]

array([[12, 13],
       [17, 18]])

Zmiana wartości w tablicy

In [9]:
A[1,2] =14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Iteracja po tablicach

In [10]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [2]:
import numpy as np


In [11]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [12]:
for row in A:
  print(row[0])

0
5
10
15


In [13]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


Iterowanie po każdym elemencie

In [14]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


# Zmiana rozmieru tablic

In [15]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
A.shape

(4, 5)

In [18]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

Odwrotność do reshape, wypłaszczenie

In [20]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Transponowanie macierzy(wiersze to kolumny i na odwrót)

In [21]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Maski logiczne

In [25]:
A=np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [26]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

Podwójny warunek tylko tą fukncją

In [28]:
np.bitwise_and(A>-5,A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [30]:
np.bitwise_or(A<-5,A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])