<a href="https://colab.research.google.com/github/DomSarr/data_science_example_1/blob/main/wprowadzenie/numpy_stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


suma wszytskiego

In [4]:
price.sum()

np.float64(4650.1)

suma po pokulmnach, numer indeksu

In [5]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

suma po wierszach

In [6]:
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [7]:
np.min(price)

np.float64(11.7)

In [8]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [9]:
np.max(price)

np.float64(2000.0)

In [12]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

In [13]:
np.median(price)

np.float64(12.6)

średnia

In [14]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

odchylenie standardowe

In [18]:
np.set_printoptions(precision=4, suppress=True)
np.std(price, axis=0)

array([  0.1247,   0.2494,   0.2055,   0.411 , 408.2483])

In [19]:
np.var(price, axis=0)

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])